name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Test if Python script runs
      run: |
        python -c "
        import http.server
        import socketserver
        print('✓ All imports work correctly')
        
        # Проверяем, что порт доступен
        PORT = 8181
        print(f'✓ Server would start on port {PORT}')
        "
    
    - name: Validate syntax
      run: |
        python -m py_compile app.py
        echo "✓ Syntax is valid"